/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package eg.edu.alexu.cse.oop.draw;

/**
 *
 * @author crap
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.util.HashMap;
import javax.swing.JOptionPane;
import java.awt.Point;
import java.awt.Graphics;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.GridLayout;
import java.awt.Paint;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationTargetException;
import java.lang.reflect.Method;
import java.net.MalformedURLException;
import java.net.URL;
import java.net.URLClassLoader;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.stream.Stream;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.*;

public class Gui extends javax.swing.JFrame {

    /**
     * Creates new form Gui
     */
    public Gui() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        diaCir = new javax.swing.JDialog();
        paneProp = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnDrawCir = new javax.swing.JButton();
        txtXCir = new javax.swing.JTextField();
        txtYCir = new javax.swing.JTextField();
        txtRadCir = new javax.swing.JTextField();
        diaSqr = new javax.swing.JDialog();
        paneProp1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnDrawSqr = new javax.swing.JButton();
        txtXSqr = new javax.swing.JTextField();
        txtYSqr = new javax.swing.JTextField();
        txtSideSqr = new javax.swing.JTextField();
        diaRec = new javax.swing.JDialog();
        paneProp2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        btnDrawRec = new javax.swing.JButton();
        txtXRec = new javax.swing.JTextField();
        txtYRec = new javax.swing.JTextField();
        txtLenRec = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtWidRec = new javax.swing.JTextField();
        diaMove = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtXMove = new javax.swing.JTextField();
        txtYMove = new javax.swing.JTextField();
        diaLine = new javax.swing.JDialog();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        btnDrawLine = new javax.swing.JButton();
        txtX1 = new javax.swing.JTextField();
        txtY1 = new javax.swing.JTextField();
        txtLen = new javax.swing.JTextField();
        diaTri = new javax.swing.JDialog();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        btnDrawTri = new javax.swing.JButton();
        txtX1Tri = new javax.swing.JTextField();
        txtY1Tri = new javax.swing.JTextField();
        txtBase = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        diaCopy = new javax.swing.JDialog();
        btnOk = new javax.swing.JButton();
        paneList = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        txtXCopy = new javax.swing.JTextField();
        txtYCopy = new javax.swing.JTextField();
        diaColor = new javax.swing.JDialog();
        BtnColor = new javax.swing.JButton();
        btnFill = new javax.swing.JButton();
        diaPlug = new javax.swing.JDialog();
        txtIn = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        diaDraw = new javax.swing.JDialog();
        btnDrawSh = new javax.swing.JButton();
        panel = new javax.swing.JPanel();
        jDialog1 = new javax.swing.JDialog();
        fc = new javax.swing.JFileChooser();
        panAll = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        comboList = new javax.swing.JComboBox<>();
        jPanel1 = new javax.swing.JPanel();
        btnRedo = new javax.swing.JButton();
        btnUndo = new javax.swing.JButton();
        btnRmv = new javax.swing.JButton();
        moveBtn = new javax.swing.JButton();
        btnCopy = new javax.swing.JButton();
        btnCC = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnSquare = new javax.swing.JButton();
        btnCir = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        BtnLin = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        paneDraw = new javax.swing.JPanel();

        jLabel3.setText("X");

        jLabel4.setText("Y");

        jLabel5.setText("Radius");

        btnDrawCir.setText("Draw");
        btnDrawCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawCirActionPerformed(evt);
            }
        });

        txtXCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXCirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panePropLayout = new javax.swing.GroupLayout(paneProp);
        paneProp.setLayout(panePropLayout);
        panePropLayout.setHorizontalGroup(
            panePropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePropLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panePropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(76, 76, 76)
                .addGroup(panePropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtXCir)
                    .addComponent(txtYCir)
                    .addComponent(txtRadCir, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panePropLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDrawCir)
                .addContainerGap())
        );
        panePropLayout.setVerticalGroup(
            panePropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panePropLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(panePropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtXCir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(panePropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtYCir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panePropLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtRadCir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnDrawCir)
                .addContainerGap())
        );

        javax.swing.GroupLayout diaCirLayout = new javax.swing.GroupLayout(diaCir.getContentPane());
        diaCir.getContentPane().setLayout(diaCirLayout);
        diaCirLayout.setHorizontalGroup(
            diaCirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaCirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        diaCirLayout.setVerticalGroup(
            diaCirLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaCirLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneProp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel6.setText("X");

        jLabel7.setText("Y");

        jLabel8.setText("Sidelength");

        btnDrawSqr.setText("Draw");
        btnDrawSqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawSqrActionPerformed(evt);
            }
        });

        txtXSqr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXSqrActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout paneProp1Layout = new javax.swing.GroupLayout(paneProp1);
        paneProp1.setLayout(paneProp1Layout);
        paneProp1Layout.setHorizontalGroup(
            paneProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProp1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneProp1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDrawSqr))
                    .addGroup(paneProp1Layout.createSequentialGroup()
                        .addGroup(paneProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(76, 76, 76)
                        .addGroup(paneProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtXSqr)
                            .addComponent(txtYSqr)
                            .addComponent(txtSideSqr, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE))
                        .addGap(0, 113, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneProp1Layout.setVerticalGroup(
            paneProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProp1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(paneProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtXSqr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(paneProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtYSqr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(paneProp1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtSideSqr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                .addComponent(btnDrawSqr)
                .addContainerGap())
        );

        javax.swing.GroupLayout diaSqrLayout = new javax.swing.GroupLayout(diaSqr.getContentPane());
        diaSqr.getContentPane().setLayout(diaSqrLayout);
        diaSqrLayout.setHorizontalGroup(
            diaSqrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaSqrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneProp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        diaSqrLayout.setVerticalGroup(
            diaSqrLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaSqrLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneProp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel9.setText("X");

        jLabel10.setText("Y");

        jLabel11.setText("Length");

        btnDrawRec.setText("Draw");
        btnDrawRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawRecActionPerformed(evt);
            }
        });

        txtXRec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXRecActionPerformed(evt);
            }
        });

        jLabel12.setText("Width");

        javax.swing.GroupLayout paneProp2Layout = new javax.swing.GroupLayout(paneProp2);
        paneProp2.setLayout(paneProp2Layout);
        paneProp2Layout.setHorizontalGroup(
            paneProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProp2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, paneProp2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnDrawRec))
                    .addGroup(paneProp2Layout.createSequentialGroup()
                        .addGroup(paneProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addGap(76, 76, 76)
                        .addGroup(paneProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtLenRec, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(txtXRec, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                            .addComponent(txtYRec)
                            .addComponent(txtWidRec))
                        .addGap(0, 140, Short.MAX_VALUE)))
                .addContainerGap())
        );
        paneProp2Layout.setVerticalGroup(
            paneProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneProp2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(paneProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtXRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(paneProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtYRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addGap(32, 32, 32)
                .addGroup(paneProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtLenRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(paneProp2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtWidRec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addComponent(btnDrawRec)
                .addContainerGap())
        );

        javax.swing.GroupLayout diaRecLayout = new javax.swing.GroupLayout(diaRec.getContentPane());
        diaRec.getContentPane().setLayout(diaRecLayout);
        diaRecLayout.setHorizontalGroup(
            diaRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaRecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneProp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        diaRecLayout.setVerticalGroup(
            diaRecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaRecLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneProp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel13.setText("New X");

        jLabel14.setText("New Y");

        jButton2.setText("Move");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        txtXMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtXMoveActionPerformed(evt);
            }
        });

        txtYMove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtYMoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaMoveLayout = new javax.swing.GroupLayout(diaMove.getContentPane());
        diaMove.getContentPane().setLayout(diaMoveLayout);
        diaMoveLayout.setHorizontalGroup(
            diaMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaMoveLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(diaMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(diaMoveLayout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtYMove, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(diaMoveLayout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                        .addComponent(txtXMove, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(114, 114, 114))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaMoveLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(34, 34, 34))
        );
        diaMoveLayout.setVerticalGroup(
            diaMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaMoveLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(diaMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(diaMoveLayout.createSequentialGroup()
                        .addGroup(diaMoveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtXMove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addComponent(jLabel14))
                    .addComponent(txtYMove, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 121, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(40, 40, 40))
        );

        jLabel15.setText("Starting X");

        jLabel16.setText("Starting Y");

        jLabel17.setText("Length");

        btnDrawLine.setText("Draw");
        btnDrawLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawLineActionPerformed(evt);
            }
        });

        txtX1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaLineLayout = new javax.swing.GroupLayout(diaLine.getContentPane());
        diaLine.getContentPane().setLayout(diaLineLayout);
        diaLineLayout.setHorizontalGroup(
            diaLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaLineLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diaLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(diaLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtLen, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtY1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(90, 90, 90))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaLineLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDrawLine)
                .addGap(25, 25, 25))
        );
        diaLineLayout.setVerticalGroup(
            diaLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaLineLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(diaLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(txtX1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(diaLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(txtY1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(diaLineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(txtLen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71)
                .addComponent(btnDrawLine)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        jLabel19.setText("X1");

        jLabel20.setText("Y1");

        jLabel21.setText("base");

        jLabel22.setText("height");

        btnDrawTri.setText("Draw");
        btnDrawTri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawTriActionPerformed(evt);
            }
        });

        txtX1Tri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtX1TriActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaTriLayout = new javax.swing.GroupLayout(diaTri.getContentPane());
        diaTri.getContentPane().setLayout(diaTriLayout);
        diaTriLayout.setHorizontalGroup(
            diaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaTriLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(diaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel20)
                    .addComponent(jLabel19)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22))
                .addGap(89, 89, 89)
                .addGroup(diaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtX1Tri, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                    .addComponent(txtY1Tri)
                    .addComponent(txtBase)
                    .addComponent(txtHeight))
                .addContainerGap(163, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaTriLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnDrawTri)
                .addGap(54, 54, 54))
        );
        diaTriLayout.setVerticalGroup(
            diaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaTriLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtX1Tri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19))
                .addGap(15, 15, 15)
                .addGroup(diaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtY1Tri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(diaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(diaTriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(86, 86, 86)
                .addComponent(btnDrawTri)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        btnOk.setText("Ok");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        jLabel25.setText("X");

        jLabel26.setText("Y");

        javax.swing.GroupLayout paneListLayout = new javax.swing.GroupLayout(paneList);
        paneList.setLayout(paneListLayout);
        paneListLayout.setHorizontalGroup(
            paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(paneListLayout.createSequentialGroup()
                        .addComponent(jLabel25)
                        .addGap(41, 41, 41)
                        .addComponent(txtXCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(paneListLayout.createSequentialGroup()
                        .addComponent(jLabel26)
                        .addGap(42, 42, 42)
                        .addComponent(txtYCopy)))
                .addContainerGap(255, Short.MAX_VALUE))
        );
        paneListLayout.setVerticalGroup(
            paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(paneListLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(txtXCopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(paneListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(txtYCopy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(149, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout diaCopyLayout = new javax.swing.GroupLayout(diaCopy.getContentPane());
        diaCopy.getContentPane().setLayout(diaCopyLayout);
        diaCopyLayout.setHorizontalGroup(
            diaCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaCopyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(diaCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaCopyLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnOk))
                    .addComponent(paneList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        diaCopyLayout.setVerticalGroup(
            diaCopyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaCopyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(paneList, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOk)
                .addContainerGap())
        );

        BtnColor.setText("Color");
        BtnColor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnColorActionPerformed(evt);
            }
        });

        btnFill.setText("Fill Color");
        btnFill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFillActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaColorLayout = new javax.swing.GroupLayout(diaColor.getContentPane());
        diaColor.getContentPane().setLayout(diaColorLayout);
        diaColorLayout.setHorizontalGroup(
            diaColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaColorLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(BtnColor, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(btnFill)
                .addGap(90, 90, 90))
        );
        diaColorLayout.setVerticalGroup(
            diaColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaColorLayout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(diaColorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnColor)
                    .addComponent(btnFill))
                .addContainerGap(207, Short.MAX_VALUE))
        );

        txtIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInActionPerformed(evt);
            }
        });

        jLabel27.setText("Please Enter Class Name");

        jButton5.setText("Browse...");
        jButton5.setActionCommand("Brows Shape");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout diaPlugLayout = new javax.swing.GroupLayout(diaPlug.getContentPane());
        diaPlug.getContentPane().setLayout(diaPlugLayout);
        diaPlugLayout.setHorizontalGroup(
            diaPlugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaPlugLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(txtIn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(65, 65, 65))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaPlugLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(38, 38, 38))
        );
        diaPlugLayout.setVerticalGroup(
            diaPlugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaPlugLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(diaPlugLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel27))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 151, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addGap(40, 40, 40))
        );

        btnDrawSh.setText("OK");
        btnDrawSh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDrawShActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout diaDrawLayout = new javax.swing.GroupLayout(diaDraw.getContentPane());
        diaDraw.getContentPane().setLayout(diaDrawLayout);
        diaDrawLayout.setHorizontalGroup(
            diaDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(diaDrawLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(288, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaDrawLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnDrawSh)
                .addGap(40, 40, 40))
        );
        diaDrawLayout.setVerticalGroup(
            diaDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, diaDrawLayout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 162, Short.MAX_VALUE)
                .addComponent(btnDrawSh)
                .addContainerGap())
        );

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDialog1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Drawing Area");

        comboList.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                comboListMouseMoved(evt);
            }
        });
        comboList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboListMouseClicked(evt);
            }
        });
        comboList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboListActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Modify"));

        btnRedo.setText("Redo");
        btnRedo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRedoActionPerformed(evt);
            }
        });

        btnUndo.setText("Undo");
        btnUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUndoActionPerformed(evt);
            }
        });

        btnRmv.setText("Remove");
        btnRmv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRmvActionPerformed(evt);
            }
        });

        moveBtn.setText("Move");
        moveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBtnActionPerformed(evt);
            }
        });

        btnCopy.setText("Copy");
        btnCopy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCopyActionPerformed(evt);
            }
        });

        btnCC.setText("Colorize");
        btnCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCCActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRedo, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRmv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(moveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCopy, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCC))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRedo)
                    .addComponent(btnUndo)
                    .addComponent(btnRmv)
                    .addComponent(moveBtn)
                    .addComponent(btnCopy)
                    .addComponent(btnCC)))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Shapes"));

        btnSquare.setText("Square");
        btnSquare.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSquareActionPerformed(evt);
            }
        });

        btnCir.setText("Circle");
        btnCir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCirActionPerformed(evt);
            }
        });

        jButton1.setText("Rectangle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        BtnLin.setText("lineSegment");
        BtnLin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnLinActionPerformed(evt);
            }
        });

        jButton4.setText("Triangle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Install Plugin");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton6.setText("New Shape");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnSquare)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BtnLin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCir, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSquare)
                    .addComponent(jButton1)
                    .addComponent(BtnLin)
                    .addComponent(btnCir)
                    .addComponent(jButton4)
                    .addComponent(jButton3)
                    .addComponent(jButton6))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panAllLayout = new javax.swing.GroupLayout(panAll);
        panAll.setLayout(panAllLayout);
        panAllLayout.setHorizontalGroup(
            panAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAllLayout.createSequentialGroup()
                .addGroup(panAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAllLayout.createSequentialGroup()
                        .addGroup(panAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panAllLayout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(comboList, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2))
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panAllLayout.setVerticalGroup(
            panAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panAllLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(panAllLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panAllLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panAllLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboList, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout paneDrawLayout = new javax.swing.GroupLayout(paneDraw);
        paneDraw.setLayout(paneDrawLayout);
        paneDrawLayout.setHorizontalGroup(
            paneDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 773, Short.MAX_VALUE)
        );
        paneDrawLayout.setVerticalGroup(
            paneDrawLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 301, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panAll, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(paneDraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(paneDraw, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCirActionPerformed
        // TODO add your handling code here:
        /*JFrame window = new JFrame();
        window.setTitle("Properties");
        window.setSize(200,200);
        window.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        window.setVisible(true);
        window.setLayout(null);
        
        JLabel lblX = new JLabel("X");
        JLabel lblY = new JLabel("Y");
        JLabel lblRad = new JLabel("Radius");
        lblX.setSize(100,25);
        lblY.setSize(100,25);
        lblRad.setSize(150,25);
        lblX.setLocation(10,0);
        lblY.setLocation(10,20);
        lblRad.setLocation(10,40);
        
        JTextField txtX = new JTextField("");
        JTextField txtY = new JTextField("");
        JTextField txtRad = new JTextField("");
        
        txtX.setSize(100,25);
        txtY.setSize(100,25);
        txtRad.setSize(100,25);
        
        txtX.setLocation(60,0);
        txtY.setLocation(60,20);
        txtRad.setLocation(60,40);
        
        JButton btnDraw = new JButton("Draw");
        btnDraw.setSize(100,25);
        btnDraw.setLocation(75,130);
        
        window.add(lblX);
        window.add(lblY);
        window.add(lblRad);
        window.add(txtX);
        window.add(txtY);
        window.add(txtRad);
        window.add(btnDraw);*/
        
        /*CircleGui CG = new CircleGui();
        CG.setVisible(true);
        setEnabled(false);
        Circle cir = new Circle();
        Point position = cir.getPosition();
        setEnabled(true);
        Graphics g = paneDraw.getGraphics();
        int radius = 20;
        g.drawOval(position.x, position.y , radius, radius);*/
        
        diaCir.setVisible(true);
        diaCir.setSize(300,300);
        diaCir.setTitle("Circle Properties");
    }//GEN-LAST:event_btnCirActionPerformed
    
    private void btnSquareActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSquareActionPerformed
        // TODO add your handling code here:
        diaSqr.setVisible(true);
        diaSqr.setSize(300,300);
        diaSqr.setTitle("Square Properties");
    }//GEN-LAST:event_btnSquareActionPerformed

    private void btnDrawCirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawCirActionPerformed
        // TODO add your handling code here:
        
        Shape cir = new Circle();
        DEngine d = new DEngine();
      
        Map properties = cir.getProperties();
        int x,y;
        double radius;
        x = Integer.parseInt(txtXCir.getText());
        y = Integer.parseInt(txtYCir.getText());
        radius = Float.parseFloat(txtRadCir.getText());

        properties.put("radius", radius);
   
        cir.setProperties(properties);
        Point position = new Point(x,y);
        
        
        cir.setPosition(position);
        Graphics canvas = paneDraw.getGraphics();
        canvas.clearRect(0, 0, 1000, 1000);
        d.addShape(cir);
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
        System.out.println(d.shapeName);
        d.refresh(canvas);
        diaCir.dispose();
        
    }//GEN-LAST:event_btnDrawCirActionPerformed

    private void txtXCirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXCirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXCirActionPerformed

    private void btnDrawSqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawSqrActionPerformed
        // TODO add your handling code here:
        Shape sqr = new Square();
        DEngine d = new DEngine();
      
        Map properties = sqr.getProperties();
        int x,y;
        double side;
        x = Integer.parseInt(txtXSqr.getText());
        y = Integer.parseInt(txtYSqr.getText());
        side = Float.parseFloat(txtSideSqr.getText());

        properties.put("side", side);
   
        sqr.setProperties(properties);
        Point position = new Point(x,y);
        
        
        sqr.setPosition(position);
        Graphics canvas = paneDraw.getGraphics();
        canvas.clearRect(0, 0, 1000, 1000);
        d.addShape(sqr);
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
        System.out.println(d.shapeName);
        d.refresh(canvas);
        diaSqr.dispose();
    }//GEN-LAST:event_btnDrawSqrActionPerformed

    private void txtXSqrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXSqrActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXSqrActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        diaRec.setVisible(true);
        diaRec.setSize(300,300);
        diaRec.setTitle("Rectangle Properties");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnDrawRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawRecActionPerformed
        // TODO add your handling code here:
        
        Graphics canvas = paneDraw.getGraphics();
        canvas.clearRect(0, 0, 1000, 1000);
        Rectangle rect = new Rectangle();
        Map properties = rect.getProperties();
        double length, width;
        int x, y;
        x = Integer.parseInt(txtXRec.getText());
        y = Integer.parseInt(txtYRec.getText());
        length = Float.parseFloat(txtLenRec.getText());
        width = Float.parseFloat(txtWidRec.getText());
        properties.put("length", length);
        properties.put("width", width);
        Point position = new Point (x,y);
        rect.setPosition(position);
        DEngine d = new DEngine();
        d.addShape(rect);
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
        d.refresh(canvas);
        System.out.println(d.shapeName);
        diaRec.dispose();
    }//GEN-LAST:event_btnDrawRecActionPerformed

    private void txtXRecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXRecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXRecActionPerformed

    private void comboListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboListActionPerformed
        // TODO add your handling code here:

 
    }//GEN-LAST:event_comboListActionPerformed

    private void comboListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboListMouseClicked
        // TODO add your handling code here:



    }//GEN-LAST:event_comboListMouseClicked

    private void comboListMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboListMouseMoved
       
        // TODO add your handling code here:

  
        
    }//GEN-LAST:event_comboListMouseMoved

    private void btnUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUndoActionPerformed
        // TODO add your handling code here:
        DEngine d = new DEngine();
        Graphics canvas = paneDraw.getGraphics();
        canvas.clearRect(0, 0, 1000, 1000);


        d.undo(); 
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
        d.refresh(canvas);
    }//GEN-LAST:event_btnUndoActionPerformed

    private void btnRedoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRedoActionPerformed
        // TODO add your handling code here:
        DEngine d = new DEngine();
        Graphics canvas = paneDraw.getGraphics();
        d.redo();
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
        canvas.clearRect(0, 0, 1000, 1000);
        d.refresh(canvas);
    }//GEN-LAST:event_btnRedoActionPerformed

    private void btnRmvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRmvActionPerformed
        // TODO add your handling code here:
        int i = comboList.getSelectedIndex();
        System.out.println(i);
        DEngine d = new DEngine();
        
        if(comboList.getSelectedItem()!=null && comboList.getSelectedItem()!="Selected"){
            d.removeShape(DEngine.shapes.get(i));
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
            Graphics canvas = paneDraw.getGraphics();
            canvas.clearRect(0, 0, 1000, 1000);
            d.refresh(canvas);
            System.out.println(DEngine.shapeName);
            comboList.removeAllItems();

        }
        
        
        
    }//GEN-LAST:event_btnRmvActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int  i = comboList.getSelectedIndex();
        int x , y;
        x = Integer.parseInt(txtXMove.getText());
        y = Integer.parseInt(txtYMove.getText());
        
        Point position = new Point(x,y);
        
        DEngine.shapes.get(i).setPosition(position);
        
        Graphics canvas = paneDraw.getGraphics();
        canvas.clearRect(0, 0, 1000, 1000);
        DEngine d = new DEngine();
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
        d.refresh(canvas);
        diaMove.dispose();
        
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtXMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtXMoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtXMoveActionPerformed

    private void txtYMoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtYMoveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtYMoveActionPerformed

    private void moveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBtnActionPerformed
        // TODO add your handling code here:
        if(comboList.getSelectedItem()!=null && comboList.getSelectedItem()!="Selected"){
            diaMove.setVisible(true);
        diaMove.setSize(300,300);
        diaMove.setTitle("New Co-Ordinates");
        }
        
    }//GEN-LAST:event_moveBtnActionPerformed

    private void BtnColorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnColorActionPerformed
        // TODO add your handling code here:
  
        diaColor.dispose();
        JColorChooser jcc = new JColorChooser();
        Color c = JColorChooser.showDialog(null, "Please Select a Color" ,Color.RED);
        int i = comboList.getSelectedIndex();
        System.out.println(i);
        DEngine d = new DEngine();
        //d.removeShape(DEngine.shapes.get(i));
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
        Graphics canvas = paneDraw.getGraphics();
        canvas.clearRect(0, 0, 1000, 1000);
            //canvas.setColor(c);
            
            //canvas.setColor(c);
        DEngine.shapes.get(i).setColor(c);
            //DEngine.shapes.get(i).draw(canvas);
        d.refresh(canvas);
        diaColor.dispose();
            
            
           
            
            
            
            
            
            
            
            
        
        
        
    }//GEN-LAST:event_BtnColorActionPerformed

    private void BtnLinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnLinActionPerformed
        // TODO add your handling code here:
        diaLine.setVisible(true);
        diaLine.setSize(400,400);
        diaLine.setTitle("LineSegment Properties");
        
    }//GEN-LAST:event_BtnLinActionPerformed

    private void txtX1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX1ActionPerformed

    private void btnDrawLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawLineActionPerformed
        // TODO add your handling code here:
        
        lineSegment ln = new lineSegment();
        DEngine d = new DEngine();
        Map properties = ln.getProperties();
        
        int x1,y1;
        double len;
        x1 = Integer.parseInt(txtX1.getText());
        y1 = Integer.parseInt(txtY1.getText());
        len = Float.parseFloat(txtLen.getText());

        properties.put("length", len);

        Point position = new Point(x1,y1);
        ln.setPosition(position);
        
        Graphics canvas = paneDraw.getGraphics();
        canvas.clearRect(0, 0, 1000, 1000);
        d.addShape(ln);
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
        System.out.println(d.shapeName);
        d.refresh(canvas);
        diaLine.dispose();
        
        
        
        
        
    }//GEN-LAST:event_btnDrawLineActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        diaTri.setVisible(true);
        diaTri.setSize(400,400);
        diaTri.setTitle("Triangle Properties");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnCopyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCopyActionPerformed
        if(comboList.getSelectedItem()!=null && comboList.getSelectedItem()!="Selected"){
            diaCopy.setSize(300,300);
            diaCopy.setVisible(true);
        }

    }//GEN-LAST:event_btnCopyActionPerformed

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed

        try {
            int  i = comboList.getSelectedIndex();
            Shape newShape = (Shape) DEngine.shapes.get(i).clone();
            int x , y;
            x = Integer.parseInt(txtXCopy.getText());
            y = Integer.parseInt(txtYCopy.getText());
            Point position = new Point(x,y);
            newShape.setPosition(position);
            DEngine d = new DEngine();
            d.addShape(newShape);
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
            Graphics canvas = paneDraw.getGraphics();
            canvas.clearRect(0, 0, 1000, 1000);
            
            d.refresh(canvas);
        } catch (CloneNotSupportedException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        diaCopy.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnFillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFillActionPerformed
        // TODO add your handling code here:
        diaColor.dispose();
        JColorChooser jcc = new JColorChooser();
        Color c = JColorChooser.showDialog(null, "Please Select a Color" ,Color.RED);
        int i = comboList.getSelectedIndex();
        System.out.println(i);
        DEngine d = new DEngine();
        //d.removeShape(DEngine.shapes.get(i));
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
            Graphics canvas = paneDraw.getGraphics();
            canvas.clearRect(0, 0, 1000, 1000);
            //canvas.setColor(c);
            
            //canvas.setColor(c);
            DEngine.shapes.get(i).setFillColor(c);
            //DEngine.shapes.get(i).draw(canvas);
            d.refresh(canvas);
            
        diaColor.dispose();
        
            
        
    }//GEN-LAST:event_btnFillActionPerformed

    private void btnCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCCActionPerformed
        // TODO add your handling code here:
        if(comboList.getSelectedItem()!=null && comboList.getSelectedItem()!="Select"){
            diaColor.setVisible(true);
            diaColor.setSize(300,300);
            diaColor.setTitle("Choose");
        }
    }//GEN-LAST:event_btnCCActionPerformed

    private void txtInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtInActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        
        // TODO add your handling code here:
        
        
        diaPlug.dispose();
  
        fc.showOpenDialog(null);
        DEngine d = new DEngine();
        
        List URLS = new ArrayList();
        try {
            URLS.add(fc.getSelectedFile().toURI().toURL());
        } catch (MalformedURLException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        URLClassLoader urlClassLoader = new URLClassLoader((URL[]) URLS.toArray(new URL[URLS.size()]));
        
        Class newShape;
        
        try {
            newShape = urlClassLoader.loadClass("eg.edu.alexu.cse.oop.draw." + txtIn.getText());
            String className = "eg.edu.alexu.cse.oop.draw." + txtIn.getText();
            Class c = Class.forName(className, rootPaneCheckingEnabled, urlClassLoader);
            d.installPluginShape(c);
            jButton6.setText(txtIn.getText());
        try {
            URLS.add(fc.getSelectedFile().toURI().toURL());
        } catch (MalformedURLException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        Class newShape2;
        try {
            newShape2 = urlClassLoader.loadClass("eg.edu.alexu.cse.oop.draw." + txtIn.getText());
            Constructor cons = newShape2.getConstructor();
            Object newShapeObj = cons.newInstance();
            //Graphics canvas = paneDraw.getGraphics();
            //canvas.clearRect(0, 0, 300, 300);
            //Method getProperties = newShape.getMethod("getProperties",x);
            //getProperties.invoke(newShapeObj,y);
            
            
            Map <String , Double> properties = new HashMap<String, Double>();
            //Shape clone = (Shape) d.shapes.get(i);
            //map = newShape.getProperties;
            
            //jframe
            
            JFrame F = new JFrame("Please Choose Properties");
            F.setVisible(true);
            F.setSize(400,400);
            F.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            JPanel P = new JPanel(new GridBagLayout());
            JPanel X = new JPanel();
            
            JButton b1= new JButton("OK");
            b1.setVisible(true);
            
            P.add(b1);
            F.add(X);
            F.add(P,BorderLayout.SOUTH);
            
            
           
            Method getProperties = newShape2.getMethod("getProperties"); //getProperties
            properties = (Map) getProperties.invoke(newShapeObj);
            
            X.setLayout(new GridLayout(properties.size()+2,2));

            JTextField [] txtList = new JTextField[properties.size()+2];
            JLabel [] lblList = new JLabel[properties.size()+2];
            int j=2;
            
            lblList[0] = new JLabel("X");
            txtList[0] = new JTextField();
            lblList[1] = new JLabel("Y");
            txtList[1] = new JTextField();
            X.add(lblList[0]);
            X.add(txtList[0]);
            X.add(lblList[1]);
            X.add(txtList[1]);
            for(String key : properties.keySet()){
            lblList[j] = new JLabel(key);
            txtList[j] = new JTextField();

            X.add(lblList[j]);
            X.add(txtList[j]);  
            j++;
            }
            b1.addActionListener(new ActionListener(){
                // here is where u put actions for OK Button
                private void actionPreformed(ActionEvent e) {
                    
                }

                @Override
                public void actionPerformed(ActionEvent e) {
                    F.dispose();
                    String className = "eg.edu.alexu.cse.oop.draw." + txtIn.getText();
                    try {
                        Class c = Class.forName(className, rootPaneCheckingEnabled, urlClassLoader);
                        Map properties = (Map)getProperties.invoke(newShapeObj);
                        double [] values = new double[properties.size()+2];
                        int x, y;
                        x = Integer.parseInt(txtList[0].getText());
                        y = Integer.parseInt(txtList[1].getText());
                    for(int i = 2; i<properties.size()+2; i++){
                        System.out.println(lblList[i].getText());
                        properties.put(lblList[i].getText(), Double.parseDouble(txtList[i].getText()));
                    }
                    // setProperties
                    Class[] propertiesParameter = new Class[]{Map.class};
                    
                    Object[] propertiesArgs = new Object[]{new HashMap(properties)};
                    Method setProperties = newShape2.getMethod("setProperties",propertiesParameter);
                    setProperties.invoke(newShapeObj,propertiesArgs);
                    
                    Graphics canvas = paneDraw.getGraphics();
                    Point position = new Point(x,y);
                    //setPosition
                    Class[] positionParameter = new Class[]{Point.class};
                    Object[] positionArgs = new Object[]{new Point(position)};
                    Method setPosition = newShape2.getMethod("setPosition",positionParameter);
                    setPosition.invoke(newShapeObj, positionArgs);
                        
                    canvas.clearRect(0, 0, 1000, 1000);
                    d.addShape((Shape) newShapeObj);//we need shape
                    DEngine d = new DEngine();
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
                    d.refresh(canvas);
                    System.out.println(d.shapeName);
                    } catch (ClassNotFoundException | IllegalAccessException | IllegalArgumentException | InvocationTargetException | NoSuchMethodException | SecurityException ex) {
                        Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    /*int x,y,i=1;
                    double[] z = new double[properties.size()];
                    for(int j = 0; j<properties.size();j+=2){
                    z[j] = Float.parseFloat(txtList[j].getText()); //z[even] = x
                    z[i] = Float.parseFloat(txtList[j].getText());//z[odd] = y
                    properties.put("z[j]", z[j]);
                    properties.put("z[j]", z[i]);
                    i+=2;
                    }*/ 
                    
                    /*int x,y,i=1;
                    double[] z = new double[properties.size()];
                    for(int j = 0; j<properties.size();j+=2){
                       
                        z[j] = Float.parseFloat(txtList[j].getText()); //z[even] = x
                        z[i] = Float.parseFloat(txtList[j].getText());//z[odd] = y
                        properties.put("z[j]", z[j]);
                        properties.put("z[j]", z[i]);
                        i+=2;
                    }*/
                    
                    
                }
                
                
            });
        
        

        } catch (ClassNotFoundException | NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
        
       
        
        
            
                
            
            
            
            
        
        
        
        
            
        
    }//GEN-LAST:event_jButton5ActionPerformed

    private void btnDrawShActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawShActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnDrawShActionPerformed

    private void txtX1TriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtX1TriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtX1TriActionPerformed

    private void btnDrawTriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDrawTriActionPerformed
        // TODO add your handling code here:

        Triangle Tri = new Triangle();
        DEngine d = new DEngine();
        Map properties = Tri.getProperties();

        int x1,y1;
        double base,height;
        x1 = Integer.parseInt(txtX1Tri.getText());
        y1 = Integer.parseInt(txtY1Tri.getText());
        base = Double.parseDouble(txtBase.getText());
        height = Double.parseDouble(txtHeight.getText());

        properties.put("base", base);
        properties.put("height", height);
        Point position = new Point(x1,y1);

        Tri.setPosition(position);
        Tri.setProperties(properties);
        
        Graphics canvas = paneDraw.getGraphics();
        canvas.clearRect(0, 0, 1000, 1000);
        d.addShape(Tri);
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
        d.refresh(canvas);
        System.out.println(d.shapeName);
        diaTri.dispose();
    }//GEN-LAST:event_btnDrawTriActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        diaPlug.setVisible(true);
        diaPlug.setTitle("Plug IN");
        diaPlug.setSize(400,300);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:



        List URLS = new ArrayList();
        try {
            URLS.add(fc.getSelectedFile().toURI().toURL());
        } catch (MalformedURLException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }
        URLClassLoader urlClassLoader = new URLClassLoader((URL[]) URLS.toArray(new URL[URLS.size()]));

        Class newShape;
        try {
            newShape = urlClassLoader.loadClass("eg.edu.alexu.cse.oop.draw." + txtIn.getText());
            Constructor cons = newShape.getConstructor();
            Object newShapeObj = cons.newInstance();
            //Graphics canvas = paneDraw.getGraphics();
            //canvas.clearRect(0, 0, 300, 300);
            //Method getProperties = newShape.getMethod("getProperties",x);
            //getProperties.invoke(newShapeObj,y);

            DEngine d = new DEngine();
            Map <String , Double> properties = new HashMap<String, Double>();
            //Shape clone = (Shape) d.shapes.get(i);
            //map = newShape.getProperties;

            //jframe
            JFrame F = new JFrame("Please Choose Properties");
            F.setVisible(true);
            F.setSize(400,400);
            F.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

            JPanel P = new JPanel(new GridBagLayout());
            JPanel X = new JPanel();

            JButton b1= new JButton("OK");
            b1.setVisible(true);

            P.add(b1);
            F.add(X);
            F.add(P,BorderLayout.SOUTH);

            Method getProperties = newShape.getMethod("getProperties"); //getProperties
            properties = (Map) getProperties.invoke(newShapeObj);

            X.setLayout(new GridLayout(properties.size()+2,2));

            JTextField [] txtList = new JTextField[properties.size()+2];
            JLabel [] lblList = new JLabel[properties.size()+2];
            int j=2;

            lblList[0] = new JLabel("X");
            txtList[0] = new JTextField();
            lblList[1] = new JLabel("Y");
            txtList[1] = new JTextField();
            X.add(lblList[0]);
            X.add(txtList[0]);
            X.add(lblList[1]);
            X.add(txtList[1]);
            for(String key : properties.keySet()){
                lblList[j] = new JLabel(key);
                txtList[j] = new JTextField();

                X.add(lblList[j]);
                X.add(txtList[j]);
                j++;
            }
            b1.addActionListener(new ActionListener(){
                // here is where u put actions for OK Button
                private void actionPreformed(ActionEvent e) {

                }

                @Override
                public void actionPerformed(ActionEvent e) {
                    F.dispose();
                    String className = "eg.edu.alexu.cse.oop.draw." + txtIn.getText();
                    try {
                        Class c = Class.forName(className, rootPaneCheckingEnabled, urlClassLoader);
                        Map properties = (Map)getProperties.invoke(newShapeObj);
                        double [] values = new double[properties.size()+2];
                        int x, y;
                        x = Integer.parseInt(txtList[0].getText());
                        y = Integer.parseInt(txtList[1].getText());
                        for(int i = 2; i<properties.size()+2; i++){
                            System.out.println(lblList[i].getText());
                            properties.put(lblList[i].getText(), Double.parseDouble(txtList[i].getText()));
                        }
                        // setProperties
                        Class[] propertiesParameter = new Class[]{Map.class};

                        Object[] propertiesArgs = new Object[]{new HashMap(properties)};
                        Method setProperties = newShape.getMethod("setProperties",propertiesParameter);
                        setProperties.invoke(newShapeObj,propertiesArgs);

                        Graphics canvas = paneDraw.getGraphics();
                        Point position = new Point(x,y);
                        //setPosition
                        Class[] positionParameter = new Class[]{Point.class};
                        Object[] positionArgs = new Object[]{new Point(position)};
                        Method setPosition = newShape.getMethod("setPosition",positionParameter);
                        setPosition.invoke(newShapeObj, positionArgs);

                        canvas.clearRect(0, 0, 1000, 1000);
                        d.addShape((Shape) newShapeObj);//we need shape
                        DEngine d = new DEngine();
    String[] shapeNames = new String[d.shapeName.size()];
    shapeNames = d.shapeName.toArray(shapeNames);

    DefaultComboBoxModel model = new DefaultComboBoxModel(shapeNames);
    comboList.setModel(model);
                        d.refresh(canvas);
                        System.out.println(d.shapeName);
                    } catch (ClassNotFoundException | IllegalAccessException | IllegalArgumentException | InvocationTargetException | NoSuchMethodException | SecurityException ex) {
                        Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    /*int x,y,i=1;
                    double[] z = new double[properties.size()];
                    for(int j = 0; j<properties.size();j+=2){
                        z[j] = Float.parseFloat(txtList[j].getText()); //z[even] = x
                        z[i] = Float.parseFloat(txtList[j].getText());//z[odd] = y
                        properties.put("z[j]", z[j]);
                        properties.put("z[j]", z[i]);
                        i+=2;
                    }*/

                    /*int x,y,i=1;
                    double[] z = new double[properties.size()];
                    for(int j = 0; j<properties.size();j+=2){

                        z[j] = Float.parseFloat(txtList[j].getText()); //z[even] = x
                        z[i] = Float.parseFloat(txtList[j].getText());//z[odd] = y
                        properties.put("z[j]", z[j]);
                        properties.put("z[j]", z[i]);
                        i+=2;
                    }*/

                }

            });

        } catch (ClassNotFoundException | NoSuchMethodException | SecurityException | InstantiationException | IllegalAccessException | IllegalArgumentException | InvocationTargetException ex) {
            Logger.getLogger(Gui.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton6ActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
            
        });
        

    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnColor;
    private javax.swing.JButton BtnLin;
    private javax.swing.JButton btnCC;
    private javax.swing.JButton btnCir;
    private javax.swing.JButton btnCopy;
    private javax.swing.JButton btnDrawCir;
    private javax.swing.JButton btnDrawLine;
    private javax.swing.JButton btnDrawRec;
    private javax.swing.JButton btnDrawSh;
    private javax.swing.JButton btnDrawSqr;
    private javax.swing.JButton btnDrawTri;
    private javax.swing.JButton btnFill;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnRedo;
    private javax.swing.JButton btnRmv;
    private javax.swing.JButton btnSquare;
    private javax.swing.JButton btnUndo;
    private javax.swing.JComboBox<String> comboList;
    private javax.swing.JDialog diaCir;
    private javax.swing.JDialog diaColor;
    private javax.swing.JDialog diaCopy;
    private javax.swing.JDialog diaDraw;
    private javax.swing.JDialog diaLine;
    private javax.swing.JDialog diaMove;
    private javax.swing.JDialog diaPlug;
    private javax.swing.JDialog diaRec;
    private javax.swing.JDialog diaSqr;
    private javax.swing.JDialog diaTri;
    private javax.swing.JFileChooser fc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton moveBtn;
    private javax.swing.JPanel panAll;
    private javax.swing.JPanel paneDraw;
    private javax.swing.JPanel paneList;
    private javax.swing.JPanel paneProp;
    private javax.swing.JPanel paneProp1;
    private javax.swing.JPanel paneProp2;
    private javax.swing.JPanel panel;
    private javax.swing.JTextField txtBase;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtIn;
    private javax.swing.JTextField txtLen;
    private javax.swing.JTextField txtLenRec;
    private javax.swing.JTextField txtRadCir;
    private javax.swing.JTextField txtSideSqr;
    private javax.swing.JTextField txtWidRec;
    private javax.swing.JTextField txtX1;
    private javax.swing.JTextField txtX1Tri;
    private javax.swing.JTextField txtXCir;
    private javax.swing.JTextField txtXCopy;
    private javax.swing.JTextField txtXMove;
    private javax.swing.JTextField txtXRec;
    private javax.swing.JTextField txtXSqr;
    private javax.swing.JTextField txtY1;
    private javax.swing.JTextField txtY1Tri;
    private javax.swing.JTextField txtYCir;
    private javax.swing.JTextField txtYCopy;
    private javax.swing.JTextField txtYMove;
    private javax.swing.JTextField txtYRec;
    private javax.swing.JTextField txtYSqr;
    // End of variables declaration//GEN-END:variables
}
